---
- name: Monta diretorio site do servidor NFS
  ansible.builtin.mount:
    src: 10.1.0.12:/opt/site
    path: /var/www/html
    opts: defaults
    state: mounted
    fstype: nfs
  tags: web

- name: Verifica se arquivo banco.php existe
  ansible.builtin.stat:
    path: /var/www/html/include/banco.php
  register: banco_php_file

- name: Define a configuracao do arquivo banco.php Debian/Ubuntu
  when: ansible_os_family == "Debian" and not banco_php_file.stat.exists
  ansible.builtin.template:
    src: banco.php.j2
    dest: /var/www/html/include/banco.php
    owner: www-data
    group: www-data
    mode: "0644"
  notify:
    - Restart Apache
  tags: web-debian

- name: Define a configuracao do arquivo banco.php RedHat/CentOS
  when: ansible_os_family == "RedHat" and not banco_php_file.stat.exists
  ansible.builtin.template:
    src: banco.php.j2
    dest: /var/www/html/include/banco.php
    owner: apache
    group: apache
    mode: "0644"
  notify:
    - Restart Httpd
  tags: web-redhat

- name: Verifica se arquivo index.html existe
  ansible.builtin.stat:
    path: /var/www/html/index.html
  register: index_file

- name: Remove o arquivo index.html
  when: index_file.stat.exists
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent
  tags: web

- name: Permitir no SELinux que o Apache acesse pastas montadas via NFS
  when: ansible_os_family == "RedHat"
  ansible.builtin.command:
    cmd: setsebool -P httpd_use_nfs 1
  tags: web

- name: Permitir no SELinux que o Apache faça binding na porta padrão (80)
  when: ansible_os_family == "RedHat"
  ansible.builtin.command:
    cmd: setsebool -P httpd_can_network_connect 1
  tags: web

- name: Configurar contexto do SELinux para diretórios de conteúdo do Apache
  when: ansible_os_family == "RedHat"
  ansible.builtin.command:
    cmd: semanage fcontext -a -t httpd_sys_content_t "/var/www/html(/.*)?"
  tags: web

- name: Restaurar contexto de segurança no diretório de conteúdo
  when: ansible_os_family == "RedHat"
  ansible.builtin.command:
    cmd: restorecon -Rv /var/www/html
  tags: web

- name: Garantir que o SELinux está permitindo conexões HTTP
  when: ansible_os_family == "RedHat"
  ansible.builtin.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  tags: web
